### ISSUE TITLE
Crash - Unhandled Exception System NullReferenceException in Avalonia Bitmap.cs

### ISSUE THREAD

**Issue by Geektoolkit** [Geektoolkit/DynaframeProIssues#62]
Possible avalonia bug. Was showing the 'no files found' screen according to the log, left for 2 days, then crashed.  Stack follows:

11/29/2023 23:28:50: PlaylistEngine: Calling setImage on /home/pi/Dynaframe/web/Dynaframe/assets/images/instructions_v.png
11/29/2023 23:28:50: PlaylistEngine: Playlist Manager is now showing: /home/pi/Dynaframe/web/Dynaframe/assets/images/instructions_v.png - 218 mb
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Media.Imaging.Bitmap.get_Size() in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 134
   at Avalonia.Controls.Image.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Image.cs:line 108
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 285
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 261
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 243
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 145
   at Avalonia.Layout.LayoutManager.ExecuteQueuedLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 105
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at Dynaframepro.Program.Main(String[] args)

last lines of the log were:
11/29/2023 23:28:49: PlaylistEngine: Entering PlaylistTimer_Elapsed. Refreshstate: Needed Automaticmode: True Playlist Length: 0
11/29/2023 23:28:49: PlaylistEngine: Building a fresh playlist
11/29/2023 23:28:49: PlaylistEngine: Python Plugins found, processing..2 plugins.
11/29/2023 23:28:49: PlaylistEngine: Mediafile count before plugins:..0 items.
11/29/2023 23:28:49: PlaylistEngine: Looking for items from plugin: Pixabay
11/29/2023 23:28:49: PlaylistEngine: Running commandline: /home/pi/Dynaframe/Assets/dfplugins/Pixabay/Pixabay.py
11/29/2023 23:28:50: PlaylistEngine: Calling setImage on /home/pi/Dynaframe/web/Dynaframe/assets/images/instructions_v.png
11/29/2023 23:28:50: PlaylistEngine: Playlist Manager is now showing: /home/pi/Dynaframe/web/Dynaframe/assets/images/instructions_v.png - 218 mb

**Comment by Geektoolkit** [comment]
Closing, we've rewritten this about 3 times by now
